-- Existing MEMORY table
CREATE TABLE IF NOT EXISTS MEMORY (
    userid TEXT NOT NULL,
    data TEXT NOT NULL,
    timestamp DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- Existing HISTORY table
CREATE TABLE IF NOT EXISTS HISTORY (
    owner TEXT NOT NULL,
    userid TEXT NOT NULL,
    message TEXT NOT NULL,
    timestamp DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- Bot personality base
CREATE TABLE IF NOT EXISTS BOT_PROFILE (
    name TEXT PRIMARY KEY
);

-- Goals tied to bot
CREATE TABLE IF NOT EXISTS BOT_GOALS (
    botname TEXT NOT NULL,
    goal TEXT NOT NULL,
    FOREIGN KEY (botname) REFERENCES BOT_PROFILE(name) ON DELETE CASCADE
);

-- Traits tied to bot
CREATE TABLE IF NOT EXISTS BOT_TRAITS (
    botname TEXT NOT NULL,
    trait TEXT NOT NULL,
    FOREIGN KEY (botname) REFERENCES BOT_PROFILE(name) ON DELETE CASCADE
);

-- Likes tied to bot
CREATE TABLE IF NOT EXISTS BOT_LIKES (
    botname TEXT NOT NULL,
    like TEXT NOT NULL,
    FOREIGN KEY (botname) REFERENCES BOT_PROFILE(name) ON DELETE CASCADE
);

-- Dislikes tied to bot
CREATE TABLE IF NOT EXISTS BOT_DISLIKES (
    botname TEXT NOT NULL,
    dislike TEXT NOT NULL,
    FOREIGN KEY (botname) REFERENCES BOT_PROFILE(name) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS BOT_SELECTION (
    userid TEXT PRIMARY KEY,
    botname TEXT NOT NULL,
    timestamp DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (botname) REFERENCES BOT_PROFILE(name) ON DELETE CASCADE
);



CREATE TABLE IF NOT EXISTS LASTFM_SESSIONS (
    userid TEXT PRIMARY KEY,        
    lastfm_username TEXT NOT NULL,  
    session_key TEXT NOT NULL,      -- Last.fm session key for API calls
    timestamp DATETIME DEFAULT CURRENT_TIMESTAMP
);